name: Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2      
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run singe hop tests
      run: |
        export PYTHONPATH=$PWD
        nose2 -s integration_tests test_single_hop
    - name: Run multi hop tests
      run: |
        export PYTHONPATH=$PWD
        nose2 -s integration_tests test_multi_hop

